<?php
$escape = $this->plugin('escapeHtml');
$decoration = $this->themeSetting('image_decoration');
?>

<div class="assets">
  <?php foreach ($attachments as $attachment): ?>
    <?php $asset = $attachment['asset']; ?>
    <div class="asset <?php echo is_array($decoration) && in_array('asset', $decoration) ? 'decoration' : ''; ?>">
        <?php
        $altText = '';
        if ($asset) {
            $altText = method_exists($asset, 'altText') ? (string) ($asset->altText() ?: '') : '';
            if (!$altText && $attachment['caption'] !== '') {
                $altText = strip_tags($attachment['caption']);
            }
            if (!$altText) {
                $altText = ucwords(str_replace(['-', '_'], ' ', pathinfo($asset->name(), PATHINFO_FILENAME)));
            }
        }
        $assetImage = ($asset) ? $this->thumbnail($asset, 'large', ['alt' => $altText]) : '';
        ?>
        <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
        <?php if ($page): ?>
            <a href="<?php echo $escape($page->siteUrl()); ?>">
                <?php echo $assetImage; ?>
                <?php $altLinkTitle = ($attachment['alt_link_title'] !== '') ? $escape($attachment['alt_link_title']) : false; ?>
                <span class="link-title"><?php echo ($altLinkTitle) ? $altLinkTitle : $escape($page->title()); ?></span>
            </a>
        <?php else: ?>
            <?php echo $assetImage; ?>
        <?php endif; ?>
        <?php if ($attachment['caption'] !== ''): ?>
        <div class="caption"><?php echo $escape($attachment['caption']); ?></div>
        <?php endif; ?>
    </div>
  <?php endforeach; ?>
</div>
