<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');

$this->inlineScript()->appendFile($this->assetUrl('js/minimasonry.min.js'));
$this->inlineScript()->appendFile($this->assetUrl('js/browse.js'));

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$layout = $this->browseLayout();
$isGrid = $layout['isGrid'];
$bodyTruncate = $this->themeSetting('truncate_body_property');
$queryUrl = $this->url(
    'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
);

$showThumbnail = in_array('thumbnail', $this->components);
$showHeading = in_array('resource-heading', $this->components);
$showBody = in_array('resource-body', $this->components);
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
?>

<div class="preview-block clearfix">

    <?php if ($this->heading) : ?>
        <div class="preview-header">
            <h3><?php echo $this->hyperlink($this->heading, $queryUrl); ?></h3>
        </div>
    <?php endif; ?>

    <?php if ($layout['hasToggle']) : ?>
        <div class="browse-controls">
            <?php echo $this->partial('common/browse-toggle', [
                'gridState' => $layout['gridState'],
                'listState' => $layout['listState'],
            ]); ?>
        </div>
    <?php endif; ?>


    <ul class="resources <?php echo ($isGrid) ? 'resource-grid' : 'resource-list'; ?>">
        <?php foreach ($this->resources as $resource): ?>
            <?php
            $heading = $headingTerm
                ? $resource->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang])
                : null;
            ?>
            <?php echo $this->partial('common/resource-card', [
                'resource' => $resource,
                'isGrid' => $isGrid,
                'valueLang' => $valueLang,
                'liClass' => $this->resourceType,
                'decorationClass' => $layout['decorationClass'],
                'bodyTerm' => $bodyTerm,
                'bodyTruncate' => $bodyTruncate,
                'heading' => $heading,
                'showThumbnail' => $showThumbnail,
                'showHeading' => $showHeading,
                'showBody' => $showBody,
            ]); ?>
        <?php endforeach; ?>
    </ul>

    <?php
    if ($this->linkText) :
        echo $this->hyperlink($this->linkText, $queryUrl, ['class' => 'browse-all']);
    endif;
    ?>

</div>
